### ISSUE TITLE
✨ Implement faker's localization

### ISSUE THREAD

**Issue by johannchopin** [johannchopin/restapify#39]
Lets handle [faker's localisation](https://github.com/Marak/faker.js#localization).

TODO:

- [x] ✨read `locale` from the restapify instance params
- [x] ✨ be sure that the `locale` is in the list
- [x] ✨ add a setLocale method that will update the `locale` and also the API
- [x] ✨ read `locale` from the config file if present
- [x] ✨ read `locale` from the CLI params if present
- [x] ✅ test the implementation

**Comment by saneinsane** [comment]
What about having two more events for pre- and postProcessing the response? With the preProcessing event we could simply set faker.locale depending on the request (Header data, URL, ...)
This would improve possibilities to customize things.

**Comment by johannchopin** [comment]
Hey @saneinsane 👋 Thanks for the proposition 👍 

Middleware would be a nice solution for that however this would go against the philosophy of restapify. I indeed created this project to avoid to define dozens of functions and conditions just to mock some simple data. The scope of restapify is the early development of a project that need a quick REST API to start. If more customisation is required then I guess it's  time to move to an alternative that offers middleware support like [mocker-api](https://github.com/jaywcjlove/mocker-api/issues) or [http-fake-backend](https://github.com/micromata/http-fake-backend).

I would like Restapify to enforce developers not to waste time mocking data since I've seen too many mocked APIs as complex as a real backend 😅 Hope you will understand this point of view 👍

**Comment by saneinsane** [comment]
Hi @johannchopin, yes I see your point. I was just eager to use it for a project where I need locales. Maybe then extending the Faker Syntax might be a better solution ("[#faker:name:firstName.en_US]"). Thanks for having a look at it!

**Comment by johannchopin** [comment]
@saneinsane My inial idea was to add a new option `locale` in the [configuration file](https://restapify.vercel.app/docs#serve-from-configuration-file) and in the CLI. What is your opinion on this?

**Comment by saneinsane** [comment]
@johannchopin To statically define a locale that would be sufficient.

In my project it is crucial to serve different languages (en and ar) from a single server to test with different directions, font families and font sizes. 
With extended faker syntax it would be possible to have different options per path, but I would end up with redundant configuration for multiple languages. 
For this scenario a dynamic solution (selecting locale depending on request properties) would be more powerful. I that case I still think, that an optional pre/postProcess Handler would give loads of possibilities without adding much complexity for implementation and usage.
An alternate approach that I used in a similar project was using [symfony expression language](https://symfony.com/doc/current/components/expression_language/syntax.html), where can access arrays, do operations and call functions. Don’t know the JS pendants, maybe [Jexl](https://github.com/TomFrost/Jexl). But this would mean a rewrite of the parser and is more a experimental suggestion.

**Comment by johannchopin** [comment]
@saneinsane Yeah you are right it would be really helpfull to change the locale on the fly without having to restart the cli with an updated configuration. I will need to find time to investigate on adding a middleware based architecture. 

An easy solution would be to add a `select` input in the [dashboard](https://restapify.vercel.app/docs#dashboard) that update the `locale` configuration for the complete API. So you will still need to manually trigger the update but I guess it's handy enough for testing a frontend interface what do you think? Another advantage is that it can be implemented easily.

**Comment by saneinsane** [comment]
@johannchopin 
For activating error responses the dashboard seems well suited to me, but language switching should be possible using my app only, without manual interaction.
Looking at [fakercloud interface](https://fakercloud.com/schemas/new) I just realized that there is a use case for extended faker syntax: often the translation is part of the same record like 
`name: {
   en: 'Product',
   de: 'Produkt'
}`

**Comment by johannchopin** [comment]
@saneinsane I guess it's important to keep in mind that restapify is there to mock data and not behaviours. The dashboard is there for that. 

I'm not against adding new features but this should not alter or complicate the ease of use and I don't see yet (maybe you do 👍) a DX friendly `in JSON` syntax for this case.

So I will add `locale` in the configuration and make it reactive with the help of the dashboard as a start.

**Comment by johannchopin** [comment]
Done via #87. Would be released in v2.4.0. See the [board](https://github.com/johannchopin/restapify/projects/4) to check the progress.
