### ISSUE TITLE
🐛 is it escaping _ on Windows?

### ISSUE THREAD

**Issue by dtsw** [johannchopin/restapify#74]
**Describe the bug**
Where?: `CLI | dashboard`
Description: When i try to access /animals (from the examples), on Windows, i need to call GET /animals_  to get the list of animals. On Linux, i can call GET /animals
Also on the Dashboard, it shows me the _ as escaped (with Backslash) on Windows:

![restapifyCapture](https://user-images.githubusercontent.com/5057391/123640844-dd1b3400-d821-11eb-97de-962f1996e441.PNG)

**Expected behavior**
I expected the same behaviour on both platforms.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version 14.17.1

**Comment by johannchopin** [comment]
Hey @dtsw 👋 thanks for opening this issue 👍

Mmh yes when you got the file path on Windows OS you got an `\` instead of `/` and didn't took this behaviour into account it as to be fixed for sure. 

Would you like to participate to this bugfix implementation?

**Comment by dtsw** [comment]
no problem, however i cannot provide a bugfix at the moment because i never did TypeScript so far. It would take too long for me...

**Comment by johannchopin** [comment]
Hey @dtsw 👋  Sorry for the late response but I finally managed to publish the v2.2.0 that fix this issue on windows. Is it in your case resolved?

**Comment by dtsw** [comment]
works very well now, thanks a lot and sorry for the late reply.

**Comment by johannchopin** [comment]
No problem thanks for the feedback and don't hesitate if you have other idea or bug to fix 👌
