### ISSUE TITLE
✨ How to deploy it to vercel ?

### ISSUE THREAD

**Issue by udahari2** [johannchopin/restapify#75]
✨ How to deploy it to vercel ?

**Comment by johannchopin** [comment]
Hey @udahari2 👋 

This library is more intended to deploy a mocked API locally than on a serverless platform like vercel. You can deploy a restapify server by using [the cli](https://restapify.vercel.app/docs#cli) or programmatically with the [Restapify class](https://restapify.vercel.app/docs#javascripts-api). So if there is a way to run one of theses and tell vercel to serve from the specified port than it's possible.

**Comment by akmal1606** [comment]
Okay, or can you help to deploy it to Heroku or any cloud provider? @johannchopin

**Comment by johannchopin** [comment]
@akmal1606 yes there should be a common solution for all the platform since restapify is express based 🤔 will let you know but it won't sadly be done until next week I guess.

**Comment by akmal1606** [comment]
Okay I think I can wait. 
because this is really helpful for me and my company. @johannchopin 
Thanks :)

**Comment by akmal1606** [comment]
btw i can deploy it to heroku but can't open the dashboard because of dashboard still hit localhost.

![Screen Shot 2021-08-12 at 20 06 27](https://user-images.githubusercontent.com/55053470/129203434-333c41de-d59b-4492-b6f1-89b3644487a3.png)

@johannchopin

**Comment by johannchopin** [comment]
@akmal1606 Nice how did you manage that? Could you share some configuration? 👍  Mmmh yes the API entrypoint is [hardcoded](https://github.com/johannchopin/restapify-dashboard/blob/main/src/axiosStore.ts#L14) to `http://localhost` in the dashboard 🤔  I opened [an issue](https://github.com/johannchopin/restapify-dashboard/issues/23) to fix it 👍

**Comment by akmal1606** [comment]
I haven't configured it much,

```
const path = require('path')
const Restapify = require('restapify').default

const apiFolderPath = path.resolve(__dirname, './mockedApi')

const rpfy = new Restapify({
  rootDir: apiFolderPath,
  openDashboard: true,
  port:process.env.PORT,
})

console.log("route", rpfy.getServedRoutes());

rpfy.on('error', ({error, message}) => {
   console.log(error + ' ' + message)
})

rpfy.run()
```

I just add this to 1 file and deploy it to Heroku as an express app.

**Comment by johannchopin** [comment]
@akmal1606 restapify v2.3.1 fixed the issue by using relative paths in the dashboard. Is it working on your side?

**Comment by johannchopin** [comment]
@akmal1606 @udahari2 I added a deployment documentation page on the [website](https://restapify.vercel.app/) that explains how to deploy a restapify API on several cloud plateforms (stackblitz, heroku, vercel and codesandbox). You can check it out at https://restapify.vercel.app/deployment.

**Comment by johannchopin** [comment]
By the way @akmal1606 (sorry I didn't find your email address on your github profile so I directly contact you here) I'm always curious to know how restapify is used and get external feedback to improve it. Is it possible to know to what extent you and your company use it, how you came across this project and what were the first impressions and limitations of the project?
