### ISSUE TITLE
✨ Add object type as allowed type in array sequence

### ISSUE THREAD

**Issue by flippingflapping** [johannchopin/restapify#76]
Hi, I left a comment about this on the dev.to post and have implemented a solution.

I'd like to inject my own fake data across multiple fields per iteration of an array sequence. I see I can currently use the for-loop's array sequence to inject each array value, but it is limited to iterating over an array of string, number or boolean type values. 

I propose allowing an object as an allowed type within the array sequence to allow iteration over an array of objects so that I can use each prop in the object and inject multiple values per iteration into the API response content. 

**Example:**
```
[
  "#for i in [{'t': 'snake', 'n': 'snek'}, {'t': 'mouse', 'n': 'mousy'}]",
  {
    "type": "[i.t]",
    "name": "[i.n]"
  },
  "#endfor"
]
```

I have implemented the feature in a branch in my fork here: https://github.com/flippingflapping/restapify/tree/feature/add-object-type-to-allowed-type-in-array-sequence 

Look forward to your feedback, cheers.

**Comment by johannchopin** [comment]
Hey @flippingflapping 👋 Thanks a lot for your help👍

Since you have already working with a fork could you create a Pull request? We could then talk there about the needed changes and make it easier to see the git diff with the `main` branch.

**Comment by flippingflapping** [comment]
No worries, I've created a pull request here: https://github.com/johannchopin/restapify/pull/77
